import React, { useState } from 'react';
import { UploadCloud, FileText, Loader2, Play } from 'lucide-react';

interface InputFormProps {
  onAnalyze: (text: string) => void;
  isAnalyzing: boolean;
}

const SAMPLE_REVIEWS = `
2023-10-01: The new update is terrible. I can't find the logout button anymore! (1/5)
2023-10-02: Love the speed improvements, but the UI looks a bit dated now. (4/5)
2023-10-05: Customer support was very helpful when I had billing issues. Thanks Sarah! (5/5)
2023-10-10: The app crashes every time I try to upload a photo. Please fix ASAP. (1/5)
2023-10-12: Generally good, but the subscription price is getting too high for what it offers. (3/5)
2023-10-15: Amazing experience! The new dark mode is sleek. (5/5)
2023-10-18: I'm frustrated. Syncing between devices never works properly. (2/5)
2023-10-20: Best productivity tool I've used this year. Highly recommend. (5/5)
2023-10-25: Why did you remove the export feature? That was essential for my workflow! (1/5)
2023-10-28: It's okay, does the job but nothing special. (3/5)
`;

export const InputForm: React.FC<InputFormProps> = ({ onAnalyze, isAnalyzing }) => {
  const [text, setText] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (text.trim()) {
      onAnalyze(text);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 md:p-8">
        <div className="flex items-center space-x-3 mb-6">
          <div className="p-3 bg-indigo-100 rounded-lg">
            <UploadCloud className="w-6 h-6 text-indigo-600" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-900">Import Reviews</h2>
            <p className="text-slate-500 text-sm">Paste your raw customer feedback below for AI analysis.</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="relative">
            <textarea
              className="w-full h-64 p-4 text-sm text-slate-700 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all resize-none font-mono"
              placeholder="Paste reviews here... (e.g. CSV content, JSON, or just plain text paragraphs)"
              value={text}
              onChange={(e) => setText(e.target.value)}
              disabled={isAnalyzing}
            />
            {!text && (
              <button
                type="button"
                onClick={() => setText(SAMPLE_REVIEWS.trim())}
                className="absolute top-4 right-4 text-xs font-medium text-indigo-600 hover:text-indigo-700 bg-indigo-50 px-3 py-1.5 rounded-md transition-colors"
              >
                Load Sample Data
              </button>
            )}
          </div>

          <div className="flex justify-end">
            <button
              type="submit"
              disabled={!text.trim() || isAnalyzing}
              className={`flex items-center space-x-2 px-6 py-3 rounded-lg font-semibold text-white transition-all transform active:scale-95 ${
                !text.trim() || isAnalyzing
                  ? 'bg-slate-300 cursor-not-allowed'
                  : 'bg-indigo-600 hover:bg-indigo-700 shadow-lg hover:shadow-indigo-500/30'
              }`}
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>Analyzing Data...</span>
                </>
              ) : (
                <>
                  <FileText className="w-5 h-5" />
                  <span>Generate Report</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
        <div className="p-4 bg-white/50 rounded-lg border border-slate-100">
          <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-3">
            <Play className="w-5 h-5 text-blue-600" />
          </div>
          <h3 className="font-semibold text-slate-900">Instant Trends</h3>
          <p className="text-xs text-slate-500 mt-1">Visualize sentiment changes over time automatically.</p>
        </div>
        <div className="p-4 bg-white/50 rounded-lg border border-slate-100">
          <div className="w-10 h-10 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-3">
            <FileText className="w-5 h-5 text-emerald-600" />
          </div>
          <h3 className="font-semibold text-slate-900">Executive Summary</h3>
          <p className="text-xs text-slate-500 mt-1">Get top 3 actionable insights generated by AI.</p>
        </div>
        <div className="p-4 bg-white/50 rounded-lg border border-slate-100">
          <div className="w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-3">
            <UploadCloud className="w-5 h-5 text-purple-600" />
          </div>
          <h3 className="font-semibold text-slate-900">Deep Understanding</h3>
          <p className="text-xs text-slate-500 mt-1">Powered by Gemini 3 Pro with Thinking Mode.</p>
        </div>
      </div>
    </div>
  );
};