import React from 'react';
import { AlertTriangle, CheckCircle, Info } from 'lucide-react';
import { ActionableItem } from '../types';

interface SummaryCardProps {
  items: ActionableItem[];
}

export const SummaryCard: React.FC<SummaryCardProps> = ({ items }) => {
  const getIcon = (priority: string) => {
    switch (priority) {
      case 'High': return <AlertTriangle className="w-5 h-5 text-rose-500" />;
      case 'Medium': return <Info className="w-5 h-5 text-amber-500" />;
      case 'Low': return <CheckCircle className="w-5 h-5 text-emerald-500" />;
      default: return <Info className="w-5 h-5 text-slate-500" />;
    }
  };

  const getBadgeColor = (priority: string) => {
    switch (priority) {
      case 'High': return 'bg-rose-100 text-rose-700';
      case 'Medium': return 'bg-amber-100 text-amber-700';
      case 'Low': return 'bg-emerald-100 text-emerald-700';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 h-full">
      <div className="flex items-center space-x-2 mb-6">
        <div className="p-2 bg-indigo-100 rounded-lg">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
        </div>
        <h3 className="text-lg font-bold text-slate-900">Executive Summary</h3>
      </div>

      <div className="space-y-4">
        {items.map((item, idx) => (
          <div key={idx} className="group p-4 rounded-lg border border-slate-100 bg-slate-50 hover:bg-white hover:border-indigo-100 hover:shadow-md transition-all duration-300">
            <div className="flex justify-between items-start mb-2">
              <h4 className="font-semibold text-slate-900 pr-4">{item.title}</h4>
              <span className={`text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full ${getBadgeColor(item.priority)}`}>
                {item.priority}
              </span>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">{item.description}</p>
          </div>
        ))}
      </div>
      
      <div className="mt-6 pt-4 border-t border-slate-100 flex justify-end">
        <span className="text-xs text-slate-400 flex items-center">
            Generated by Gemini 3 Pro
        </span>
      </div>
    </div>
  );
};